### ISSUE TITLE
Load imageview from remote source

### ISSUE THREAD

**Issue by saintjab** [nshmura/SnappyImageViewer#1]
@nshmura, I love this library. It is possible to implement setImageViewURL as well. That would be awesome.

**Comment by nshmura** [comment]
@saintjab Thank you for your proposal !
I think many application already uses image library like [picasso](https://github.com/square/picasso), So I feel it's better to use image library to load remote images.
I made a sample of using picasso library to load image. Would you please see [this commit](https://github.com/nshmura/SnappyImageViewer/commit/c1d9f4b650bf2bbb348674060d8852b2c01dee41)?

**Comment by saintjab** [comment]
Thanks @nshmura , the Picasso example is working now. Good work, thanks for the help.

**Comment by nshmura** [comment]
@saintjab great! :tada:
