### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by varunsngl** [nshmura/SnappyImageViewer#3]
HI,

First of all very thanks for making this library. But the app crashes on closing image.

I'm using fragments and after swiping the image. App crashes.

Thanks

**Comment by nshmura** [comment]
Cloud you show me your stacktrace?

**Comment by varunsngl** [comment]
I've removed the library from the project. Sorry I'll create a new project and share in a few days.

**Comment by nshmura** [comment]
@varunsngl oh, ok! let me know your library 👍
